[package]
name = "PruebaWeb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlx = { version = "0.6.2", features = ["mysql", "runtime-tokio-native-tls", "macros"] }
tokio = { version = "1.21.2", features = ["full"] }
text_io = "0.1.10"
clap = { version = "4.0.24", features = ["derive"] }